/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId/route'

// Create/Update Routes

const StoresStoreIdRouteRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/stores/$storeId': typeof StoresStoreIdRouteRoute
}

export interface FileRoutesByTo {
  '/stores/$storeId': typeof StoresStoreIdRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/stores/$storeId': typeof StoresStoreIdRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/stores/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/stores/$storeId'
  id: '__root__' | '/stores/$storeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  StoresStoreIdRouteRoute: typeof StoresStoreIdRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  StoresStoreIdRouteRoute: StoresStoreIdRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/stores/$storeId"
      ]
    },
    "/stores/$storeId": {
      "filePath": "stores/$storeId/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
